### ISSUE TITLE
Emitting Effects based on Temperature

### ISSUE THREAD

**Issue by gomker** [jrodrigv/DestructionEffects#8]
Spanner and I have been thinking about an additional feature. This would be initially for Tank hulls in which we would emit some damage effects based on how much "damage" or temperature the part has taken. 
Many of the Hulls for tanks or boats are quite large and what I propose is the following logic

conditions
-  if part is tagged with an identifying fields, say "DestructionEffect"
-  If part max temp is Greater than (>) %85

  Then emit smoke, damage effects.

The use case would be say a Hellfire missile hits a tank, did not destroy, some damage effects emitted.

The question I cannot answer is instead of emitting from the broken "joint" could we emit from a part layer or something similar.

**Comment by SpannerMonkey** [comment]
Should the part layer not be possible would it be possible to emit from a cfg defined FX node?, 

Without actually having physical transforms (unity GameObjects) it could be defined using the legacy node system, and would be fairly easy , though time consuming to set up with node helper.  (used in the editor to visualize and position  stack type nodes and export the obtained positional values) 

As most of the parts are very similar in size there's a good chance that there'd be a one size fits all for a lot of the parts .

 And even if  the positions  not be perfect, as long as the nodes fit inside the shell  the effect will render through the vehicle, regardless of colliders etc.

Though how to define 1 of four nodes ( hand wavium number)  as the one that should be smoking/burning? 

I recall reading somewhere ( on a forum)  about a bit of code or cfg that could place active transforms (like thrust transforms for example)   in a model prefab( whats saved in the editor)  been digging still not found it.

**Comment by jrodrigv** [comment]
I need to test the idea, I think it should be possible to attach flames to all parts. I'm bit worried about the possible performance hit though (but we can make it configurable).

**Comment by gomker** [comment]
The idea would be attaching it to parts with only certain tags and we could use a config file to configure those tags. Usually the Tanks are large single parts.

**Comment by ghost** [comment]
I support this idea as I was the one that first requested it.

But maybe lower the temp needed for FX, to say like, 50% or 60% of max temp.

**Comment by jrodrigv** [comment]
I think it should not be difficult to do, however I will need to figure out
how to show only smoke, maybe with a new set of textures..

**Comment by gomker** [comment]
my main concern was "where" to emit from as the current code emits from the joint, as Spanner pointed out his question on the FX Node (note I have no idea what that means). After that its all logic , if else when greater than etc... I think the current effects are fine, smoke and fire, just so we can get a proof of concept going. Spanner can help with making sure there is the proper nodes to target.

**Comment by SpannerMonkey** [comment]
Ok,  This is how from the parts dept I think we should proceed.

The stock squad docking port module has a variable for node name to indicate which node is a docking port 
A node can be defined by either of the following methods 
node_stack_FX = -0.5, 0, 0, -1, 0, 0, 0   
OR
	NODE
{
name = FX here FxNodeID
transform = FX here FxNodeID
size = 1 //   stock range 0 - 7  perhaps controlling smoke amount, larger = more ?
method = FIXED_JOINT 
}

And the module code looks like 
`MODULE
	{
		name =blah blah
		anchorName = blah
		ejectionForce = blah
		explosiveNodeID = FX here
	}`

Now the first method of determining the node can be retrofitted to anything , the second has to be done at part creation.   
So create a module that can use a reference node  from the cfg. I  do appreciate that DFX is not at this time a fully fledged part module 

``MODULE
	{
		name = moduleDFX
		emit = true/false // maybe superfluous 
		emitForce = blah? amount of FX ?
		FxNodeID = FX here
	}``

It would be nice if it could accept multiple transforms/Nodes of the same name.  As i propose for a tank there would be 5 nodes   engine right, engine left.  drive right ,drive left  and turret  nodes. 

While this is not perfect and FX could come from any or all nodes , it does present a workable and testable system. 

 Obviously it could be done the long winded way and have X transform/nodes uniquely named and have X amount of DFX modules in the cfg, messy but much more versatile 

It seems to me that using a defined node rather than checking for parts is the low energy way to go 

Please let me know if there any terms not understood, as there are two languages in this team, part and code :)

**Comment by ghost** [comment]
@jrodrigv Do you want me to try to make new textures?

**Comment by ghost** [comment]
I just got an idea that's probaly taking it to far but we can try...

Maybe different types of FX at different times for things like fuel tanks? For example:

20-30% of max heat = White smoke
40-50%  of max heat = Black smoke
55% and higher = Fire

If possible, I think you should make it so that the smoke goes higher when something is on the ground, because it's hard to tell if the enemy tank is dead with the parts being covered with smoke and not being able to see the parts.

I can start making textures right now, and if we are going to use my damage system idea, then I can make the white smoke texture. However, I'm going to use the legacy FX textures to make the textures unless you guys plan to change the way textures are emitted.

**Comment by MuricanJeb** [comment]
any news?

**Comment by MuricanJeb** [comment]
Is anyone still awware of thise issue? I'd really like this to be added

**Comment by ghost** [comment]
Is this still being worked on?

**Comment by jrodrigv** [comment]
I think at the moment no one is working on it.

**Comment by ghost** [comment]
Any news?

**Comment by jrodrigv** [comment]
Hi @MuricanJeb I'm not working on this at the moment.

**Comment by ghost** [comment]
Anything new about this?

**Comment by gomker** [comment]
We will come back to this after we have finished the damage / armor update. Can't really work on it until then

**Comment by SpannerMonkey** [comment]
Also relevant, as the damage system is no longer heat based, it seems that other methods will be more useful

**Comment by gomker** [comment]
If the armor balance doesn't lead me to drink excessively (more than I do already) then this will be the first thing I'd like to look at doing

**Comment by ghost** [comment]
I think we can close this issue now, right?

**Comment by theonegalen** [comment]
Awwww. :(
